const TOGGLE_MEMORIZED = 'TOGGLE_MEMORIZED'
const REMOVE_WORD = 'REMOVE_WORD'
const ADD_WORD = 'ADD_WORD'
const TOGGLE_FORM = 'TOGGLE_FORM'
const SET_FILTER_MODE = 'SET_FILTER_MODE'

export const actionType = {TOGGLE_MEMORIZED , REMOVE_WORD ,ADD_WORD,TOGGLE_FORM,SET_FILTER_MODE}